spring:
  application:
    name: flashcard-app-server
  datasource:
    url: jdbc:postgresql://localhost:5432/flashcarddb
    username: annie
    password: card123
  flyway:
    enabled: true
    locations: classpath:db/migration/structure, classpath:db/migration/data
    validate-on-migrate: true
